version: '3.9'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend-api

  backend-api:
    build: ./backend-api-go
    ports:
      - "8080:8080"
    depends_on:
      - backend-worker

  backend-worker:
    build: ./backend-worker-python
    ports:
      - "8000:8000"
